- type: disease
  id: DiseaseFoodPoisoning
  name: disease-DiseaseFoodPoisoning-name
  desc: disease-DiseaseFoodPoisoning-desc
  spreadFlags: [NonContagious]
  stageProb: 0.03
  cureSteps:
  - !type:CureReagent
    cureChance: 0.1
    requirements:
    - reagentId: ChickenSoup # TODO: need to add a dish.
  - !type:CureWait
    requiredTicks: 300
  stages:
  - stage: 1
    sensations:
    - sensation: disease-sensation-queasy
    - sensation: disease-sensation-stomach-weird
  - stage: 2
    sensations:
    - sensation: disease-sensation-stomach-ache
    - sensation: disease-sensation-nausea
    symptoms:
    - symptom: SymptomEmoteGroan
      probability: 0.1
  - stage: 3
    sensations:
    - sensation: disease-sensation-stomach-hurt
    - sensation: disease-sensation-sick
    symptoms:
    - symptom: SymptomVomiting
    - symptom: SymptomEmoteGroan
      probability: 0.1
    - symptom: SymptomEmoteMoan
      probability: 0.1

- type: disease
  id: DiseaseNarcolepsySyndrome
  name: disease-DiseaseNarcolepsySyndrome-name
  desc: disease-DiseaseNarcolepsySyndrome-desc
  spreadFlags: [Airborne]
  airborneInfect: 0.01
  cureSteps:
  - !type:CureReagent
    cureChance: 0.08
    requirements:
    - reagentId: Haloperidol
  - !type:CureWait
    requiredTicks: 300
    waitChance: 0.5
  stages:
  - stage: 1
    sensations:
    - sensation: disease-sensation-sleepy
  - stage: 2
    sensations:
    - sensation: disease-sensation-sleepy-2
    - sensation: disease-sensation-sleepy-3
    symptoms:
    - symptom: SymptomNarcolepsy

- type: disease
  id: DiseaseAMIV
  name: disease-DiseaseAMIV-name
  desc: disease-DiseaseAMIV-desc
  spreadFlags: [Contact]
  contactInfect: 0.005
  contactDeposit: 0.05
  cureSteps:
  - !type:CureReagent
    requirements:
    - reagentId: JuiceBanana
      quantity: 5
  stages:
  - stage: 1
    # no-op
  - stage: 2
    sensations:
    - sensation: disease-sensation-sick
    - sensation: disease-sensation-banana-compulsion
  - stage: 3
    cureSteps:
      - !type:CureWait
        requiredTicks: 200
        waitChance: 0.5
    sensations:
    - sensation: disease-sensation-sick
    - sensation: disease-sensation-banana-compulsion
    symptoms:
    - symptom: SymptomMonkeyShout
    - symptom: SymptomGeneticDamage
